server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # รองรับ React Router (ถ้าหา path ไม่เจอ ให้กลับไปที่ index.html)
        try_files $uri $uri/ /index.html; 
    }

    # Proxy ส่ง API ไปหา Backend Container
    location /api/ {
        proxy_pass http://backend:5000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}