version: '3.8'

services:
  # Database Service (MySQL)
  db:
    image: mysql:8.0
    container_name: asset_tracker_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: factory_assets
      MYSQL_USER: developer
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306" # ใช้ 3307 เพื่อไม่ให้ชนกับ MySQL ในเครื่องคุณ (3306)
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: